# Generated by Django 3.0 on 2019-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoCli', '0002_auto_20191205_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
    ]
