# Generated by Django 3.0 on 2019-12-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoCli', '0003_remove_cliente_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=50)),
            ],
        ),
    ]
